# Generated by Django 4.1.3 on 2022-11-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='imgs/default.png', null=True, upload_to='profile_images/'),
        ),
    ]
