# Generated by Django 4.1.3 on 2022-11-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_comment_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
