# Generated by Django 4.1.3 on 2022-11-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_feed_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="original_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="original_feed_images/"
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="transfer_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="transfer_feed_images/"
            ),
        ),
    ]
